ANTHROPIC_BASE_URL=http: //localhost:11434/v1 \
ANTHROPIC_AUTH_TOKEN=ollama \
ANTHROPIC_API_KEY="" \
ANTHROPIC_MODEL=gemma4:26b \
ANTHROPIC_DEFAULT_OPUS_MODEL=gemma4:26b \
ANTHROPIC_DEFAULT_SONNET_MODEL=gemma4:26b \
ANTHROPIC_DEFAULT_HAIKU_MODEL=gemma4:26b \
CLAUDE_CODE_SUBAGENT_MODEL=gemma4:26b \
claude "$@"
EOF
chmod +x claude-local.sh